<?php die("Access Denied"); ?>#x#a:5:{s:4:"body";s:6560:"<div class="item-page" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="en-GB" />
	
		
						
	
	
				
								<div itemprop="articleBody">
		<p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.344; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Methvin is an online estimating and procurement portal</span></p>
<p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.344; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Designed and developed to be intuitive and user friendly.</span></p>
<p dir="ltr" style="margin-top: 0pt; margin-bottom: 0pt; line-height: 1.344; text-align: center;"><span style="font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Methvin is a project management and estimation tool designed for the construction industry. It will make your life considerably easier; estimating projects, publishing tenders and producing comparisons, and helping to find potential business opportunities. </span></p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp<iframe width="560" height="315" src="https://www.youtube.com/embed/gOqtHPJ14Jk" frameborder="0" allowfullscreen></iframe></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your online estimating application</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Good software supports your workflow. Great software improves it.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">In today&rsquo;s competitive estimating environment, &ldquo;Methvin Estimating Software&rdquo; allows you to quickly and accurately generate quality cost estimates and winning bids.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">This estimation advantage is made possible by allowing you to link worksheets to multiple tasks, set variables and to break tasks into sub schedules for fast accurate pricing. Making your workflow more efficient and improve your margin analysis.</span></p>
<p><a href="products/estimating-software" title="Online estimating software"><img src="images/estimating_with_sub-schedules-amit-1.png" alt="estimating with sub schedules amit 1" class="fadein_img" style="display: block; margin-left: auto; margin-right: auto;" /></a></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">The most advanced tendering portal</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Facilitating a faster procurement cycle!</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your potential contractors and subcontractors will find the submission process easier and faster, because they can access your documentation and send their responses via your portal.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Increased transparency! You&rsquo;ll have complete oversight over what&rsquo;s happening during each step of the tendering process.</span></p>
<p>&nbsp;<a href="products/tendering-portal" title="Online tendering portal"><img src="images/online_tendering.png" alt="online tendering" width="400" height="270" class="fadein_img" style="margin-right: auto; margin-left: auto; display: block;" /></a></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">New Business Opportunities</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Search our server with our innovative filters.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">A finger on the pulse of your sector! Our daily email notifications will alert you to what&rsquo;s going on in your sector; for instance, who&rsquo;s calling for tenders, who&rsquo;s likely to be seeking subcontractors, trends in procurement of your services, and so on. Great market intelligence.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;">&nbsp;</p>
<p><a href="design" title="Pricing opportunities"><img src="images/pricing_opportunities.png" alt="pricing opportunities" width="380" height="324" class="fadein_img" style="display: block; margin-left: auto; margin-right: auto;" /></a></p>	</div>

	
							</div>
";s:4:"head";a:11:{s:5:"title";s:71:"Methvin Estimating Software – online construction estimating software";s:11:"description";s:133:"The Power of Methvin | Online construction estimating software, for user-friendly bidding and analysis of large construction projects";s:4:"link";s:0:"";s:8:"metaTags";a:2:{s:10:"http-equiv";a:1:{s:12:"content-type";s:24:"text/html; charset=utf-8";}s:4:"name";a:3:{s:8:"keywords";s:366:"Estimating Software, Bidding Software, Construction Estimating Software, Tender Portal, online, web-based, cloud, construction estimating software, Highways, Bridges, Tunnels, Elevated Highways, Water and Sewer Line, Earthwork, Concrete, and Excavation, Landscaping, Golf Course Construction, Demolition, Mining, Railroad, Marine, Utility, estimator, bidding, bidpro";s:6:"rights";N;s:6:"author";s:10:"Super User";}}s:5:"links";a:0:{}s:11:"styleSheets";a:0:{}s:5:"style";a:0:{}s:7:"scripts";a:4:{s:27:"/media/jui/js/jquery.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:34:"/media/jui/js/jquery-noconflict.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:35:"/media/jui/js/jquery-migrate.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:27:"/media/system/js/caption.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}}s:6:"script";a:1:{s:15:"text/javascript";s:79:"jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});";}s:6:"custom";a:0:{}s:10:"scriptText";a:0:{}}s:13:"mime_encoding";s:9:"text/html";s:7:"pathway";a:0:{}s:6:"module";a:0:{}}