<?php die("Access Denied"); ?>#x#a:5:{s:4:"body";s:11651:"<div class="item-page" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="en-GB" />
	
		
						
	
	
				
								<div itemprop="articleBody">
		<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">The most advanced tendering portal</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Good software supports your workflow. Great software improves it.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your potential contractors and subcontractors will find the submission process easier and faster, because they can access your documentation and send their responses via your portal.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Increased transparency! You&rsquo;ll have complete oversight over what&rsquo;s happening during each step of the process.</span></p>
<p style="text-align: center;"><a href="http://54.86.146.45:8080/Methvin/"><img onmouseout="this.src='/images/tendingnew.png'" class="fadein_img" onmouseover="this.src='/images/tendingnew-2.png'" alt="" src="/images/tendingnew.png" style="opacity: 1;"></a></p>

<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Publish your tenders online</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your tender exposure is your choice!</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Our online &ldquo;Tender Box&rdquo; will reduce your procurement cycle. Provide greater probity; you&rsquo;ll have a complete audit trail for all aspects of the process. Easy, Cost-Effective Communication - Respond to contractor or supplier queries via our &lsquo;notice to tenderer&rsquo; facility. This saves you time and means every contractor or supplier has the same, up-to-date information. </span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/Up_Cloud-1.png" alt="publish tenders online" class="fadein_img"/></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Tender comparison made easy</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Dynamically linked pricing schedules, make the automation of tender comparisons possible.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Once your contractors or subcontractors have submitted their prices. Their bids are automatically placed into the online comparison spreadsheet adjacent to other contractor&rsquo;s submitted prices. This provides a clear comparison of tenders, item by item.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/tender_comparisons.png" alt="tender comparisons" class="fadein_img"/></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">New Business Opportunities</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Search our server by trades and region, with our innovative filters.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">A finger on the pulse of your sector - Our daily email notifications will alert you to what&rsquo;s going on in your sector, for instance, who&rsquo;s calling for tenders, who&rsquo;s likely to be seeking subcontractors, trends in procurement of your services, and so on. Great market intelligence. </span></p>
<p style="text-align: center;"><a href="http://54.86.146.45:8080/Methvin/"><img onmouseout="this.src='/images/pricing_opportunities-1.png'" class="fadein_img" onmouseover="this.src='/images/pricing_opportunities-2.png'" alt="" src="/images/pricing_opportunities-1.png" style="opacity: 1;"></a></p>

<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your <a href="index.php/products/estimating-software">online estimating</a> application</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Good software supports your workflow. Great software improves it.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">In today&rsquo;s competitive construction estimating environment, &ldquo;Methvin Estimating Software&rdquo; allows you to quickly and accurately generate quality cost estimates and winning bids.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">This estimation advantage is made possible by allowing you to link worksheets to multiple tasks, set variables and breaking tasks into sub schedules for fast accurate pricing. This makes your workflow more efficient and improve your margin analysis.</span></p>
<p style="text-align: center;"><a href="/products/estimating-software"><img onmouseout="this.src='/images/estimating_with_sub-schedules-1new.png'" class="fadein_img" onmouseover="this.src='/images/estimating_with_sub-schedules-2new.png'" alt="" src="/images/estimating_with_sub-schedules-1new.png" style="opacity: 1;"></a></p>

<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Electronic &ldquo;Tender Box&rdquo;</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">The worlds most advanced tender delivery system.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">When you&rsquo;ve completed your tender preparation, deliver it to your client using the online electronic Tender Box. Your tender is delivered to the right place on time.</span></p>
<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/tenders-2.png" alt="cloud based tender box" class="fadein_img"/></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Project Management</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">The worlds most advanced pricing system.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Methvin allows the contractor and subcontractor to send online claims to their clients. All variations can be tracked online by all. The contractor can print subcontract certification reports to evaluate their subcontract claims each month.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/project_management.png" alt="project management" class="fadein_img"/></span></p>
<p>&nbsp;</p>
<p>&nbsp;</p> 	</div>

	
	
<ul class="pager pagenav">
	<li class="previous">
		<a href="/products/estimating-software" rel="prev">
			<span class="icon-chevron-left"></span> Prev		</a>
	</li>
	<li class="next">
		<a href="/products" rel="next">
			Next <span class="icon-chevron-right"></span>		</a>
	</li>
</ul>
							</div>
";s:4:"head";a:11:{s:5:"title";s:26:"Online estimating software";s:11:"description";s:61:"Estimating Software | online construction estimating software";s:4:"link";s:0:"";s:8:"metaTags";a:2:{s:10:"http-equiv";a:1:{s:12:"content-type";s:24:"text/html; charset=utf-8";}s:4:"name";a:3:{s:8:"keywords";s:43:"Estimating, Software, online, construction,";s:6:"rights";N;s:6:"author";s:10:"Super User";}}s:5:"links";a:0:{}s:11:"styleSheets";a:0:{}s:5:"style";a:0:{}s:7:"scripts";a:4:{s:27:"/media/jui/js/jquery.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:34:"/media/jui/js/jquery-noconflict.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:35:"/media/jui/js/jquery-migrate.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:27:"/media/system/js/caption.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}}s:6:"script";a:1:{s:15:"text/javascript";s:79:"jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});";}s:6:"custom";a:0:{}s:10:"scriptText";a:0:{}}s:13:"mime_encoding";s:9:"text/html";s:7:"pathway";a:1:{i:0;O:8:"stdClass":2:{s:4:"name";s:6:"Design";s:4:"link";s:62:"index.php?option=com_content&view=article&id=409&Itemid=316532";}}s:6:"module";a:0:{}}