<?php die("Access Denied"); ?>#x#a:5:{s:4:"body";s:11955:"<div class="item-page" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="en-GB" />
	
		
						
	
	
				
								<div itemprop="articleBody">
		<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Your online estimating application</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Good software supports your workflow. Great software improves it.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">In today&rsquo;s competitive construction estimating environment, &ldquo;Methvin Estimating Software&rdquo; allows you to quickly and accurately generate quality cost estimates and winning bids.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">This estimation advantage is made possible by allowing you to link worksheets to multiple tasks, set variables and to break tasks into sub schedules for fast accurate pricing. Making your workflow more efficient and improve your margin analysis.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/online_estimating_application.png" alt="online estimating application" class="" /></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Estimating with sub-schedules</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Limitless detail, infinite possibilities.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">When the client provides one item for a complex section of work, for example, a Lump Sum Item calling for the construction of a bridge, with Methvin you can change the item into a &ldquo;sub-schedule item&rdquo;. By using the Pricing Module, any items pertaining to that sub-schedule will roll up to the clients item. Under the sub-schedule you are able to add as much detail as you require, to allow you to price the item accurately. The Client report will only reflect the Lump Sum Item as requested in his schedule, in this example &ldquo;The Bridge&rdquo;.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/estimating_with_sub-schedules.png" alt="estimating with sub-schedules" class="fadein_img" /></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> Advanced estimating options</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin: 0pt -22.5pt 0pt -36pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Simple or complex pricing, or the best of both worlds.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 19px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Simple Online Estimating</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Insert your required selling or gross rate directly into the pricing schedule. This can then be printed or exported to Excel as a client's quote. All changes are saved automatically and you have successfully created your first tender in Methvin.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 19px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Complex Estimating With Worksheet</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Under each item in the schedule there is a worksheet dynamically attached. Here you can drag in resources or worksheets from the pricing accordion, decreasing your pricing time and improving the accuracy of your tender.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/advanced_estimating.png" alt="advanced estimating" class="fadein_img" /></span></p>
<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Estimating online with variables</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">This is how &ldquo;Methvin Estimating Software&rdquo; comes into its own. </span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Our complex worksheet allows you to set variables for pricing, for example the distance from a quarry to the site or the depth of a trench. When you set up a new project, with a similar item to price, all that is required is to adjust the variables to the new circumstances once again providing an accurate tender.</span></p>
<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="https://lh4.googleusercontent.com/uWZz34qDtmJ1ZnDrRBuUSSaL0Pit0KkyR53C_QYSo6dIBObxECMABeF0FWVTjdoR1ErFewPqxF5qHTKrDb4g2HJ4YFl1xhmXr4CSFgrd7dxduFcoZFm7HynPmUY-zuGAgg" alt="On-line Quote" width="160px;" height="160px;" class="fadein_img" /></span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 32px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> Estimating with Java functions</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 24px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">The Worlds most advanced pricing system.</span></p>
<p dir="ltr" style="line-height: 1.3440000057220458; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Unique to Methvin, you are able to utilise any </span><a href="http://www.w3schools.com/jsref/jsref_obj_math.asp"><span style="font-size: 16px; font-family: Verdana; color: #c90000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">function available in Java</span></a><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> to automate your complex pricing.</span><span style="font-size: 16px; font-family: Verdana; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Methvin facilitates the use of any mathematical function you can imagine.</span></p>
<p dir="ltr" style="line-height: 1.5; margin-top: 0pt; margin-bottom: 0pt; margin-left: 36pt; text-align: justify;"><span style="font-size: 15px; font-family: Arial; color: #666666; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Examples:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="list-style-type: disc; font-family: Arial; color: #666666; vertical-align: baseline; margin-left: 48px; background-color: transparent;">
<p dir="ltr" style="line-height: 1.5; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 15px; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">if ([your variable i.e. 2]&gt;5) {yes} else {no} - Returns no</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-family: Arial; color: #666666; vertical-align: baseline; margin-left: 48px; background-color: transparent;">
<p dir="ltr" style="line-height: 1.5; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 15px; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Math.round(2.5) - Returns 3</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-family: Arial; color: #666666; vertical-align: baseline; margin-left: 48px; background-color: transparent;">
<p dir="ltr" style="line-height: 1.5; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 15px; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">var x = Math.PI - Returns PI</span></p>
</li>
<li dir="ltr" style="list-style-type: disc; font-family: Arial; color: #666666; vertical-align: baseline; margin-left: 48px; background-color: transparent;">
<p dir="ltr" style="line-height: 1.5; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 15px; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">var y = Math.sqrt(16) - Returns the square root of 16 </span></p>
</li>
</ul>
<p style="text-align: center;">&nbsp;<span style="font-family: Arial; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><img src="images/java.png" alt="estimating with Java functions" class="fadein_img" /></span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>	</div>

	
							</div>
";s:4:"head";a:11:{s:5:"title";s:19:"Estimating Software";s:11:"description";s:61:"Estimating Software | online construction estimating software";s:4:"link";s:0:"";s:8:"metaTags";a:2:{s:10:"http-equiv";a:1:{s:12:"content-type";s:24:"text/html; charset=utf-8";}s:4:"name";a:3:{s:8:"keywords";s:43:"Estimating, Software, online, construction,";s:6:"rights";N;s:6:"author";s:10:"Super User";}}s:5:"links";a:0:{}s:11:"styleSheets";a:0:{}s:5:"style";a:0:{}s:7:"scripts";a:4:{s:27:"/media/jui/js/jquery.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:34:"/media/jui/js/jquery-noconflict.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:35:"/media/jui/js/jquery-migrate.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:27:"/media/system/js/caption.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}}s:6:"script";a:1:{s:15:"text/javascript";s:79:"jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});";}s:6:"custom";a:0:{}s:10:"scriptText";a:0:{}}s:13:"mime_encoding";s:9:"text/html";s:7:"pathway";a:2:{i:0;O:8:"stdClass":2:{s:4:"name";s:8:"Products";s:4:"link";s:62:"index.php?option=com_content&view=article&id=258&Itemid=316583";}i:1;O:8:"stdClass":2:{s:4:"name";s:19:"Estimating Software";s:4:"link";s:62:"index.php?option=com_content&view=article&id=410&Itemid=316584";}}s:6:"module";a:0:{}}