<?php die("Access Denied"); ?>#x#a:3:{s:4:"body";s:63071:"<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="en-gb">
	<title type="text">Concrete Work</title>
	<subtitle type="text">Estimating Software | online construction estimating software</subtitle>
	<link rel="alternate" type="text/html" href="http://www.methvin.org"/>
	<id>http://www.methvin.org/construction-production-rates/concrete-work/64-surface-finishes</id>
	<updated>2017-05-08T05:01:00+00:00</updated>
	<author>
		<name>Methvin</name>
		<email>info@methvin.org</email>
	</author>
	<generator uri="https://www.joomla.org">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="http://www.methvin.org/construction-production-rates/concrete-work/64-surface-finishes?format=feed&amp;type=atom"/>
	<entry>
		<title>Surface Finishes</title>
		<link rel="alternate" type="text/html" href="http://www.methvin.org/construction-production-rates/concrete-work/surface-finishes"/>
		<published>2012-07-28T02:43:51+00:00</published>
		<updated>2012-07-28T02:43:51+00:00</updated>
		<id>http://www.methvin.org/construction-production-rates/concrete-work/surface-finishes</id>
		<author>
			<name>Super User</name>
			<email>gush@win.co.nz</email>
		</author>
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;br class=&quot;Apple-interchange-newline&quot; /&gt;&lt;/b&gt;&lt;strong&gt;Concrete Finishing Estimating Man-hours&lt;/strong&gt;&lt;/p&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; class=&quot;telerik-reTable-4&quot; style=&quot;border-width: 0px; border-style: solid; border-collapse: collapse; font-family: Tahoma; color: #000000; text-align: left; width: 100%;&quot;&gt;&lt;colgroup&gt;&lt;col width=&quot;133&quot; style=&quot;width: 100pt;&quot; /&gt;&lt;col width=&quot;372&quot; style=&quot;width: 279pt;&quot; /&gt;&lt;col width=&quot;46&quot; style=&quot;width: 35pt;&quot; /&gt;&lt;col width=&quot;69&quot; style=&quot;width: 52pt;&quot; /&gt;&lt;col width=&quot;59&quot; style=&quot;width: 44pt;&quot; /&gt;&lt;/colgroup&gt;
&lt;tbody&gt;
&lt;tr height=&quot;35&quot; class=&quot;telerik-reTableHeaderRow-4&quot; style=&quot;border-width: 1pt 1pt 3pt; margin: 0in 0in 10pt; line-height: 17px; font-size: 11pt; font-family: Calibri, sans-serif; width: 119.7pt; background-color: #4f81bd; padding: 0in 5.4pt; color: #ffffff; height: 26.25pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableHeaderFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; height: 26.25pt; width: 100pt;&quot;&gt;Description&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 279pt;&quot;&gt;Tasks&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 35pt;&quot;&gt;Unit&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 52pt;&quot;&gt;Tradesman Hours&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 44pt;&quot;&gt;Labourer Hours&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&amp;nbsp;Surface Finishes&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Hand Trowel&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.15&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Power Float&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.18&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Broomed Finish&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.12&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Concrete Finishing Production Rates&lt;/strong&gt;&lt;/p&gt;
&lt;table border=&quot;1&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; class=&quot;telerik-reTable-4&quot; style=&quot;border-width: 1px; border-style: solid; border-collapse: collapse; font-family: Tahoma; color: #000000; text-align: left; width: 100%;&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;telerik-reTableHeaderRow-4&quot; style=&quot;border-width: 1pt 1pt 3pt; margin: 0in 0in 10pt; line-height: 17px; font-size: 11pt; font-family: Calibri, sans-serif; width: 119.7pt; background-color: #4f81bd; padding: 0in 5.4pt; color: #ffffff;&quot;&gt;
&lt;td align=&quot;center&quot; valign=&quot;middle&quot;&gt;Task / Description&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Slow&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Ave&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Fast&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;left&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;&amp;nbsp;Units&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Steel Float By Hand&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;9.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;13.9&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Wood Float By Hand&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;11.7&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;17.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;29.4&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Power Float&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;13.9&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;20.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;37.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Light Brush on Trowel&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;55.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;90.1&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;170.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Brush on Trowel Margin&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;28.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;48.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;85.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Sprayed By Pump, expose aggregate&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;65.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;95.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;145.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Wire Brush, expose aggregate&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;15.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;30.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Walls, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;5.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;8.6&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Columns, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;2.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;6.9&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Sides of Beams, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;2.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;7.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Slab Soffits, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;4.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;5.5&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Bolt Holes, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;14.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;16.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.8&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;no/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Rubdown Precast Concrete, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;18.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Scabble 3 head brush hammer, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;30.7&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;59.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;73.8&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;hrs/m2&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</summary>
		<content type="html">&lt;p&gt;&lt;b&gt;&lt;br class=&quot;Apple-interchange-newline&quot; /&gt;&lt;/b&gt;&lt;strong&gt;Concrete Finishing Estimating Man-hours&lt;/strong&gt;&lt;/p&gt;
&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; class=&quot;telerik-reTable-4&quot; style=&quot;border-width: 0px; border-style: solid; border-collapse: collapse; font-family: Tahoma; color: #000000; text-align: left; width: 100%;&quot;&gt;&lt;colgroup&gt;&lt;col width=&quot;133&quot; style=&quot;width: 100pt;&quot; /&gt;&lt;col width=&quot;372&quot; style=&quot;width: 279pt;&quot; /&gt;&lt;col width=&quot;46&quot; style=&quot;width: 35pt;&quot; /&gt;&lt;col width=&quot;69&quot; style=&quot;width: 52pt;&quot; /&gt;&lt;col width=&quot;59&quot; style=&quot;width: 44pt;&quot; /&gt;&lt;/colgroup&gt;
&lt;tbody&gt;
&lt;tr height=&quot;35&quot; class=&quot;telerik-reTableHeaderRow-4&quot; style=&quot;border-width: 1pt 1pt 3pt; margin: 0in 0in 10pt; line-height: 17px; font-size: 11pt; font-family: Calibri, sans-serif; width: 119.7pt; background-color: #4f81bd; padding: 0in 5.4pt; color: #ffffff; height: 26.25pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableHeaderFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; height: 26.25pt; width: 100pt;&quot;&gt;Description&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 279pt;&quot;&gt;Tasks&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 35pt;&quot;&gt;Unit&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 52pt;&quot;&gt;Tradesman Hours&lt;/td&gt;
&lt;td class=&quot;telerik-reTableHeaderLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed; width: 44pt;&quot;&gt;Labourer Hours&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&amp;nbsp;Surface Finishes&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Hand Trowel&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.15&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Power Float&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.18&lt;/td&gt;
&lt;/tr&gt;
&lt;tr height=&quot;20&quot; class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd; height: 15pt;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid; height: 15pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;Broomed Finish&lt;/td&gt;
&lt;td class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;m2&lt;/td&gt;
&lt;td class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid; width: 52pt;&quot;&gt;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; align=&quot;right&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed; width: 44pt;&quot;&gt;0.12&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Concrete Finishing Production Rates&lt;/strong&gt;&lt;/p&gt;
&lt;table border=&quot;1&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; class=&quot;telerik-reTable-4&quot; style=&quot;border-width: 1px; border-style: solid; border-collapse: collapse; font-family: Tahoma; color: #000000; text-align: left; width: 100%;&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;telerik-reTableHeaderRow-4&quot; style=&quot;border-width: 1pt 1pt 3pt; margin: 0in 0in 10pt; line-height: 17px; font-size: 11pt; font-family: Calibri, sans-serif; width: 119.7pt; background-color: #4f81bd; padding: 0in 5.4pt; color: #ffffff;&quot;&gt;
&lt;td align=&quot;center&quot; valign=&quot;middle&quot;&gt;Task / Description&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Slow&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Ave&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;Fast&amp;nbsp;&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;left&quot; valign=&quot;middle&quot; class=&quot;telerik-reTableHeaderLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-top-color: #999999; border-top-width: 1px; border-top-style: dashed; border-left-color: #999999; border-left-width: 1px; border-left-style: dashed;&quot;&gt;&amp;nbsp;Units&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Steel Float By Hand&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;9.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;13.9&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Wood Float By Hand&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;11.7&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;17.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;29.4&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Power Float&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;13.9&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;20.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;37.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Light Brush on Trowel&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;55.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;90.1&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;170.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Brush on Trowel Margin&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;28.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;48.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;85.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Sprayed By Pump, expose aggregate&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;65.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;95.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;145.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Surface Finishing, Wire Brush, expose aggregate&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;15.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;30.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Walls, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;5.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;8.6&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Columns, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;2.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;6.9&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Sides of Beams, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;2.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;7.0&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Slab Soffits, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;4.2&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;5.5&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Bolt Holes, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;14.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;16.8&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;25.8&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;no/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableOddRow-4&quot; style=&quot;border-width: 1pt; color: #666666; font-size: 10pt; vertical-align: top; border-bottom-style: solid; border-bottom-color: #4f81bd;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Rubdown Precast Concrete, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;18.0&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;- &amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;m2/hr&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;telerik-reTableEvenRow-4&quot; style=&quot;color: #666666; font-size: 10pt; vertical-align: top;&quot;&gt;
&lt;td class=&quot;telerik-reTableFirstCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: solid; border-bottom-style: solid;&quot;&gt;&amp;nbsp;Making Good Scabble 3 head brush hammer, prepare, shutter, pour&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;30.7&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableEvenCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;59.5&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot; class=&quot;telerik-reTableOddCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-top-style: dashed; border-left-style: dashed; border-bottom-style: solid;&quot;&gt;73.8&amp;nbsp;&lt;/td&gt;
&lt;td class=&quot;telerik-reTableLastCol-4&quot; style=&quot;padding: 0in 5.4pt; border-color: #4f81bd; border-width: 1pt; border-style: dashed solid solid dashed;&quot;&gt;&amp;nbsp;hrs/m2&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</content>
		<category term="Surface Finishes" />
	</entry>
</feed>
";s:13:"mime_encoding";s:20:"application/atom+xml";s:7:"headers";a:5:{i:0;a:2:{s:4:"name";s:12:"Content-Type";s:5:"value";s:35:"application/atom+xml; charset=utf-8";}i:1;a:2:{s:4:"name";s:7:"Expires";s:5:"value";s:29:"Wed, 17 Aug 2005 00:00:00 GMT";}i:2;a:2:{s:4:"name";s:13:"Last-Modified";s:5:"value";s:29:"Mon, 08 May 2017 05:01:00 GMT";}i:3;a:2:{s:4:"name";s:13:"Cache-Control";s:5:"value";s:62:"no-store, no-cache, must-revalidate, post-check=0, pre-check=0";}i:4;a:2:{s:4:"name";s:6:"Pragma";s:5:"value";s:8:"no-cache";}}}